allowCompoundWords: true
dictionaries:
  - cpp
  - cpp-refined
  - csharp
  - dotnet
  - en-gb
  - en-us
  - fsharp
  - game-development
  - gaming-terms
  - git
  - lorem-ipsum
  - markdown
  - misc
  - php
  - softwareTerms
  - unity
enableGlobDot: true
features:
  weighted-suggestions: true
globRoot: ${cwd}
ignorePaths:
  - .*ignore
  - .git
  - .github/CODE_OF_CONDUCT.*
  - .vscode/extensions.json
  - Assets/TextMesh Pro
  - Assets/UdonSharp
  - Assets/XR
  - cspell.config.yml
  - Packages
  - ProjectSettings
language: en,eo,ja
useGitignore: true
version: "0.2"
words:
  - dwlt
  - imgbotconfig
  - kito
  - kuron
  - kuroné
  - msaa
  - nunit
  - spatialize
  - udon
  - unityyamlmerge
  - vrchat
  - vrcsdk
  - vstuc
